name: Deploy UAT Dashboard to GitHub Pages

on:
  push:
    branches: [ main ]   # deploys when you push to main
  workflow_dispatch:     # allows manual run from Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'   # deploy the repo root (your index.html, uat.json, etc.)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
